name: 'Action 2' 
description: 'Make a POST request to get safe@ data'
inputs:
  projectId:
    description: 'projectId'
    required: true
  namespace:
    description: 'namespace'
    required: true
  stage:
    description: 'stage'
    required: false
  commit:
    description: 'commit'
    required: false
  
outputs:
  result:
    description: 'safe@ data'
runs:
  using: 'node16'
  main: 'dist/index.js'